version: '3.5'

services:
  web:
    ports:
      - "${SERVICE_PORT}:80"
    networks:
      - styx
      - loterie
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PORT: ${VIRTUAL_PORT}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}

  php:
    networks:
      - loterie
networks:
  styx:
    external: true
  loterie:
    driver: bridge
