version: '3.5'

services:
  web:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./docker/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    ports:
      - "8080:80"

  php:
    build:
      context: .
      dockerfile: ./docker/php.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www


